# Generated by Django 3.2.6 on 2021-08-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Vehicle Name')),
                ('brand', models.CharField(max_length=120, verbose_name='Brand Name')),
                ('location', models.URLField(max_length=1000)),
                ('speed', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Speed')),
                ('avg_speed', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Average Speed')),
                ('temperature', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Tempearture')),
                ('fuel_level', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Tempearture')),
                ('camera1', models.CharField(max_length=120, verbose_name='Camera 1')),
                ('camera2', models.CharField(max_length=120, verbose_name='Camera 2')),
            ],
        ),
    ]
