# Generated by Django 3.2.6 on 2021-08-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_level',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Fuel level'),
        ),
    ]
