# Generated by Django 3.2.6 on 2021-08-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_fuel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='avg_speed',
            field=models.IntegerField(verbose_name='Average Speed'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_level',
            field=models.IntegerField(verbose_name='Fuel level'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='speed',
            field=models.IntegerField(verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='temperature',
            field=models.IntegerField(verbose_name='Tempearture'),
        ),
    ]
