# Generated by Django 3.2.6 on 2021-08-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20210825_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='camera1',
            field=models.URLField(max_length=1000, verbose_name='Camera 1'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='camera2',
            field=models.URLField(max_length=1000, verbose_name='Camera 2'),
        ),
    ]
